name: ChatMonster
version: 1.4
author: burnt_apples
description: ChatMonster will gobble up all the unwanted chatter
main: io.github.burntapples.ChatMonster
commands:
    cm:
        description: ChatMonster help
        usage: /<command>
    cm clearwarnings:
        description: Remove warnings from a player
        usage: /cm clearwarnings <player>
        aliases: [cm clearw, cm cw]
    cm check:
        description: Check how many warnings a player has
        usage: /cm warnings
        aliases: [cm checkw, cm warns]
    cm warn:
        description: Give a warning to a player if CM fails to do so
        usage: /cm warn <player> <amount> <reason> 
        aliases: [cm a, cm addwarning, cm add, cm addwarn]
    cm reload:
        description: ChatMonster reload command
        usage: /cm reload
        aliases: [cm r]
    cm parse:
        description: Toggle strict parse mode for censoring per player
        usage: /cm bypass <player>
        aliases: [cm sp, cm strict, cm parsetoggle]
    cm toggle:
        description: Turn off ChatMonster
        usage: /cm toggle
    cm conf:
        description: Configure ChatMonster in-game
        usage: /cm conf
        aliases: [cm configure, cm config, cm setval]
    cm help:
        description: Access ChatMonster help
        usage: /cm help
    cm update:
      description: update the plugin
      usage: /cm update
    
permissions:
  chatmonster.*:
    description: Access to all ChatMonster permissions
    children:
      chatmonster.warn: true
      chatmonster.check: true
      chatmonster.check.own: true
      chatmonster.clearwarnings: true
      chatmonster.reload: true
      chatmonster.togglestate: true
      chatmonster.configure: true
      chatmonster.alias: true
      chatmonster.parsetoggle: true
      chatmonster.bypass.spam: true
      chatmonster.bypass.ad: true
      chatmonster.bypass.censor: true
      chatmonster.update: true
  chatmonster.warn:
    description: Allows you to add warnings to a player
    default: false
  chatmonster.check:
    description: View the amount of warnings a player has
    default: false
  chatmonster.reload:
    description: Reload ChatMonster and all of its components
    default: false
  chatmonster.clearwarnings:
    description: Clear a player's warnings
    default: false
  chatmonster.parsetoggle:
    description: allows a player to toggle scrict parse mode (for another player)
    default: false
  chatmonster.bypass.spam:
    description: Bypass spam check
    default: false
  chatmonster.bypass.ad:
    description: Bypass ad check
    default: false
  chatmonster.bypass.censor:
    description: Bypass censor check
    default: false
  chatmonster.togglestate:
    description: toggle chatmonster on/off
    default: false
  chatmonster.configure:
    description: Change ChatMonster settings in game
    default: false
  chatmonster.alias:
    description: List command aliases
    default: false
  chatmonster.update:
    description: update ChatMonster
    default: false